"use strict";
let myname = document.getElementById(`name`);
let designation = document.getElementById(`designation`);
let phone = document.getElementById(`phone`);
let email = document.getElementById(`email`);
let add = document.getElementById(`add`);
let pass1 = document.getElementById(`pass1`);
let deg1 = document.getElementById(`deg1`);
let uni1 = document.getElementById(`uni1`);
let pass2 = document.getElementById(`pass2`);
let deg2 = document.getElementById(`deg2`);
let uni2 = document.getElementById(`uni2`);
let skill1 = document.getElementById(`skill1`);
let skill2 = document.getElementById(`skill2`);
let skill3 = document.getElementById(`skill3`);
let skill4 = document.getElementById(`skill4`);
let skill5 = document.getElementById(`skill5`);
let skill6 = document.getElementById(`skill6`);
let lang1 = document.getElementById(`lang1`);
let lang2 = document.getElementById(`lang2`);
let lang3 = document.getElementById(`lang3`);
let styear = document.getElementById(`styear`);
let endyear = document.getElementById(`endyear`);
let company = document.getElementById(`company`);
let companylocation = document.getElementById(`companylocation`);
let jobtitle = document.getElementById(`jobtitle`);
let achive1 = document.getElementById(`achive1`);
let achive2 = document.getElementById(`achive2`);
let achive3 = document.getElementById(`achive3`);
let achive4 = document.getElementById(`achive4`);
let achive5 = document.getElementById(`achive5`);
let pic = document.getElementById(`pic`);
let submitBtn = document.getElementById(`submitBtn`);
let form = document.getElementById(`form`);
form?.addEventListener('submit', (event) => {
    event.preventDefault();
    localStorage.setItem("name", myname.value);
    localStorage.setItem("designation", designation.value);
    localStorage.setItem("phone", phone.value);
    localStorage.setItem("email", email.value);
    localStorage.setItem("add", add.value);
    localStorage.setItem("pass1", pass1.value);
    localStorage.setItem("deg1", deg1.value);
    localStorage.setItem("uni1", uni1.value);
    localStorage.setItem("pass2", pass2.value);
    localStorage.setItem("deg2", deg2.value);
    localStorage.setItem("uni2", uni2.value);
    localStorage.setItem("skill1", skill1.value);
    localStorage.setItem("skill2", skill2.value);
    localStorage.setItem("skill3", skill3.value);
    localStorage.setItem("skill4", skill4.value);
    localStorage.setItem("skill5", skill5.value);
    localStorage.setItem("skill6", skill6.value);
    localStorage.setItem("lang1", lang1.value);
    localStorage.setItem("lang2", lang2.value);
    localStorage.setItem("lang3", lang3.value);
    localStorage.setItem("styear", styear.value);
    localStorage.setItem("endyear", endyear.value);
    localStorage.setItem("company", company.value);
    localStorage.setItem("companylocation", companylocation.value);
    localStorage.setItem("jobtitle", jobtitle.value);
    localStorage.setItem("achive1", achive1.value);
    localStorage.setItem("achive2", achive2.value);
    localStorage.setItem("achive3", achive3.value);
    localStorage.setItem("achive4", achive4.value);
    localStorage.setItem("achive5", achive5.value);
    if (pic.files && pic.files[0]) {
        let reader = new FileReader();
        reader.addEventListener("load", () => {
            let textImg = reader.result;
            localStorage.setItem("profile_pic", textImg);
        });
        reader.readAsDataURL(pic.files[0]);
    }
    window.location.href = "./resume/index.html";
});
